# .github/workflows/npm_publish.yaml
name: Публикация в NPM

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[publish]')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Установка зависимостей
        run: npm install

      - name: Сборка библиотеки
        run: npm run build

      - name: Публикация в NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
